initial stuff

diff --git a/.github/workflows/environment_create.yml b/.github/workflows/environment_create.yml
--- a/.github/workflows/environment_create.yml
+++ b/.github/workflows/environment_create.yml
@@ -32,6 +32,9 @@ jobs:
     steps:
       - uses: actions/checkout@v3
 
+      - name: Build ADE.Tutorial
+        run: dotnet publish ./ADE.Tutorial -c Release -o ./publish && (cd ./publish && zip -r ../publish.zip .)
+
       - name: Install DevCenter CLI Extension
         run: az extension add --name devcenter --upgrade
 
@@ -41,3 +44,28 @@ jobs:
           client-id: ${{ secrets.AZURE_CLIENT_ID }}
           tenant-id: ${{ vars.AZURE_TENANT_ID }}
           subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
+
+      - name: Create Environment
+        run: |
+          az devcenter dev environment create \
+              --name ${{ env.ENVIRONMENT_NAME }} --environment-type ${{ env.ENVIRONMENT_TYPE }} \
+              --dev-center ${{ vars.AZURE_DEVCENTER }} --project ${{ vars.AZURE_PROJECT }} \
+              --catalog-name ${{ vars.AZURE_CATALOG }} --catalog-item-name ${{ vars.AZURE_CATALOG_ITEM }} \
+              --parameters '{ "name": "${{ env.ENVIRONMENT_NAME }}" }' --only-show-errors
+
+      - name: Get Environment Resource Group
+        run: |
+          environment_rg=$(az devcenter dev environment show --name ${{ env.ENVIRONMENT_NAME }} \
+              --dev-center ${{ vars.AZURE_DEVCENTER }} --project ${{ vars.AZURE_PROJECT }} \
+              --only-show-errors --query resourceGroupId --output tsv 2>&1)
+
+          if [ $? -eq 0 ]; then
+              echo "ENVIRONMENT_GROUP=$environment_rg" >> $GITHUB_ENV
+          else
+              echo "::error::az devcenter dev environment show command failed: $environment_rg"; exit 1
+          fi
+
+      - name: Deploy ADE.Tutorial
+        run: |
+          az functionapp deployment source config-zip --name ${{ env.ENVIRONMENT_NAME }} --src publish.zip \
+              --resource-group ${{ env.ENVIRONMENT_GROUP }}
