refactor workflow scripts

diff --git a/.github/workflows/environment_update.yml b/.github/workflows/environment_update.yml
--- a/.github/workflows/environment_update.yml
+++ b/.github/workflows/environment_update.yml
@@ -18,12 +18,12 @@ concurrency: ${{ github.event.number || github.ref_name }}
 jobs:
   config:
     if: github.event_name == 'pull_request' || (contains(github.event.ref, 'refs/heads') && !github.event.created)
-    name: Get Environment
+    name: Get Configuration
     uses: ./.github/workflows/environment_config.yml
 
   update_env:
     if: github.event_name == 'pull_request' || (contains(github.event.ref, 'refs/heads') && !github.event.created)
-    name: Update Environment
+    name: Update ${{ needs.config.outputs.type }} Environment
     runs-on: ubuntu-latest
 
     needs: config
@@ -49,42 +49,42 @@ jobs:
           tenant-id: ${{ vars.AZURE_TENANT_ID }}
           subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
 
-      - name: Get Environment Resource Group
+      - name: Get Resource Group
+        shell: bash {0}
         run: |
+          echo "Getting environment ${{ env.ENVIRONMENT_NAME }}..."
           environment_rg=$(az devcenter dev environment show --name ${{ env.ENVIRONMENT_NAME }} \
               --dev-center ${{ vars.AZURE_DEVCENTER }} --project ${{ vars.AZURE_PROJECT }} \
               --only-show-errors --query resourceGroupId --output tsv 2>&1)
 
-          if [ $? -eq 0 ]; then
-              environment_group=${environment_rg##*/}
-              environment_sub=${environment_rg%/resourceGroups*}
-              environment_sub=${environment_sub##*/}
-
-              echo "ENVIRONMENT_GROUP=$environment_group" >> $GITHUB_ENV
-              echo "ENVIRONMENT_SUB=$environment_sub" >> $GITHUB_ENV
-          elif [[ $environment_rg =~ "EnvironmentCannotBeFound" ]] && [[ "$ENVIRONMENT_TYPE" == "Prod" ]]; then
-
+          if [ $? -ne 0 ]; then
               # Prod (main) environment may not be created yet
-              environment_rg=$(az devcenter dev environment create \
-                  --name ${{ env.ENVIRONMENT_NAME }} --environment-type ${{ env.ENVIRONMENT_TYPE }} \
-                  --dev-center ${{ vars.AZURE_DEVCENTER }} --project ${{ vars.AZURE_PROJECT }} \
-                  --catalog-name ${{ vars.AZURE_CATALOG }} --catalog-item-name ${{ vars.AZURE_CATALOG_ITEM }} \
-                  --parameters '{ "name": "${{ env.ENVIRONMENT_NAME }}" }' --only-show-errors \
-                  --query resourceGroupId --output tsv 2>&1)
+              if [[ $environment_rg =~ "EnvironmentCannotBeFound" || $environment_rg =~ "EnvironmentNotFound" ]] && [[ "$ENVIRONMENT_TYPE" == "Prod" ]]; then
+                  echo "Environment ${{ env.ENVIRONMENT_NAME }} not found, creating..."
 
-              if [ $? -eq 0 ]; then
-                  environment_group=${environment_rg##*/}
-                  environment_sub=${environment_rg%/resourceGroups*}
-                  environment_sub=${environment_sub##*/}
+                  environment_rg=$(az devcenter dev environment create \
+                      --name ${{ env.ENVIRONMENT_NAME }} --environment-type ${{ env.ENVIRONMENT_TYPE }} \
+                      --dev-center ${{ vars.AZURE_DEVCENTER }} --project ${{ vars.AZURE_PROJECT }} \
+                      --catalog-name ${{ vars.AZURE_CATALOG }} --catalog-item-name ${{ vars.AZURE_CATALOG_ITEM }} \
+                      --parameters '{ "name": "${{ env.ENVIRONMENT_NAME }}" }' --only-show-errors \
+                      --query resourceGroupId --output tsv 2>&1)
 
-                  echo "ENVIRONMENT_GROUP=$environment_group" >> $GITHUB_ENV
-                  echo "ENVIRONMENT_SUB=$environment_sub" >> $GITHUB_ENV
+                  if [ $? -ne 0 ]; then
+                      echo "Failed to create environment ${{ env.ENVIRONMENT_NAME }}"
+                      echo "::error::az devcenter dev environment create command failed: $environment_rg"; exit 1
+                  fi
               else
-                  echo "::error::az devcenter dev environment create command failed: $environment_rg"; exit 1
+                  echo "Failed to get environment ${{ env.ENVIRONMENT_NAME }}"
+                  echo "::error::az devcenter dev environment show command failed: $environment_rg"; exit 1
               fi
-          else
-              echo "::error::az devcenter dev environment show command failed: $environment_rg"; exit 1
           fi
+
+          environment_group=${environment_rg##*/}
+          environment_sub=${environment_rg%/resourceGroups*}
+          environment_sub=${environment_sub##*/}
+
+          echo "ENVIRONMENT_GROUP=$environment_group" >> $GITHUB_ENV
+          echo "ENVIRONMENT_SUB=$environment_sub" >> $GITHUB_ENV
 
       - name: Deploy ADE.Tutorial
         run: |
